baseURL = "syahrulanuar.github.io"
languageCode = "en-us"
title = "Syahrul Anuar Repository"
theme = "Sam"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[[params.mainMenu]]
    link = "/WIP"
    text = "Works In Progress"

[[params.mainMenu]]
    link = "Nowiswhen"
    text = "Now Is When"

[[params.mainMenu]]
    link = "Contact"
    text = "Contact"